# SPDX-License-Identifier: 0BSD
"""Constants for mount(2), umount2(2) and the new mount API.

Values verified against /usr/include/sys/mount.h,
/usr/include/linux/mount.h and the AT_* bits from
/usr/include/bits/fcntl-linux.h.
"""

from __future__ import annotations

import os

__all__ = [
    "AT_EMPTY_PATH",
    "AT_FDCWD",
    "AT_NO_AUTOMOUNT",
    "AT_RECURSIVE",
    "AT_SYMLINK_FOLLOW",
    "AT_SYMLINK_NOFOLLOW",
    "FSCONFIG_CMD_CREATE",
    "FSCONFIG_CMD_CREATE_EXCL",
    "FSCONFIG_CMD_RECONFIGURE",
    "FSCONFIG_SET_BINARY",
    "FSCONFIG_SET_FD",
    "FSCONFIG_SET_FLAG",
    "FSCONFIG_SET_PATH",
    "FSCONFIG_SET_PATH_EMPTY",
    "FSCONFIG_SET_STRING",
    "FSMOUNT_CLOEXEC",
    "FSMOUNT_NAMESPACE",
    "FSOPEN_CLOEXEC",
    "FSPICK_CLOEXEC",
    "FSPICK_EMPTY_PATH",
    "FSPICK_NO_AUTOMOUNT",
    "FSPICK_SYMLINK_NOFOLLOW",
    "MNT_DETACH",
    "MNT_EXPIRE",
    "MNT_FORCE",
    "MOUNT_ATTR_ATIME_SHIFT",
    "MOUNT_ATTR_IDMAP",
    "MOUNT_ATTR_NOATIME",
    "MOUNT_ATTR_NODEV",
    "MOUNT_ATTR_NODIRATIME",
    "MOUNT_ATTR_NOEXEC",
    "MOUNT_ATTR_NOSUID",
    "MOUNT_ATTR_NOSYMFOLLOW",
    "MOUNT_ATTR_RDONLY",
    "MOUNT_ATTR_RELATIME",
    "MOUNT_ATTR_SIZE_VER0",
    "MOUNT_ATTR_STRICTATIME",
    "MOUNT_ATTR__ATIME",
    "MOVE_MOUNT_BENEATH",
    "MOVE_MOUNT_F_AUTOMOUNTS",
    "MOVE_MOUNT_F_EMPTY_PATH",
    "MOVE_MOUNT_F_SYMLINKS",
    "MOVE_MOUNT_SET_GROUP",
    "MOVE_MOUNT_T_AUTOMOUNTS",
    "MOVE_MOUNT_T_EMPTY_PATH",
    "MOVE_MOUNT_T_SYMLINKS",
    "MS_ACTIVE",
    "MS_BIND",
    "MS_BORN",
    "MS_DIRSYNC",
    "MS_I_VERSION",
    "MS_KERNMOUNT",
    "MS_LAZYTIME",
    "MS_MANDLOCK",
    "MS_MGC_MSK",
    "MS_MGC_VAL",
    "MS_MOVE",
    "MS_NOATIME",
    "MS_NODEV",
    "MS_NODIRATIME",
    "MS_NOEXEC",
    "MS_NOSUID",
    "MS_NOSYMFOLLOW",
    "MS_NOUSER",
    "MS_POSIXACL",
    "MS_PRIVATE",
    "MS_RDONLY",
    "MS_REC",
    "MS_RELATIME",
    "MS_REMOUNT",
    "MS_RMT_MASK",
    "MS_SHARED",
    "MS_SILENT",
    "MS_SLAVE",
    "MS_STRICTATIME",
    "MS_SUBMOUNT",
    "MS_SYNCHRONOUS",
    "MS_UNBINDABLE",
    "OPEN_TREE_CLOEXEC",
    "OPEN_TREE_CLONE",
    "OPEN_TREE_NAMESPACE",
    "UMOUNT_NOFOLLOW",
]

# mount(2) rwflag bits, /usr/include/linux/mount.h
MS_RDONLY = 1
MS_NOSUID = 2
MS_NODEV = 4
MS_NOEXEC = 8
MS_SYNCHRONOUS = 16
MS_REMOUNT = 32
MS_MANDLOCK = 64
MS_DIRSYNC = 128
MS_NOSYMFOLLOW = 256
MS_NOATIME = 1024
MS_NODIRATIME = 2048
MS_BIND = 4096
MS_MOVE = 8192
MS_REC = 16384
MS_SILENT = 32768  # MS_VERBOSE is deprecated, same bit
MS_POSIXACL = 1 << 16
MS_UNBINDABLE = 1 << 17
MS_PRIVATE = 1 << 18
MS_SLAVE = 1 << 19
MS_SHARED = 1 << 20
MS_RELATIME = 1 << 21
MS_KERNMOUNT = 1 << 22
MS_I_VERSION = 1 << 23
MS_STRICTATIME = 1 << 24
MS_LAZYTIME = 1 << 25

# Internal kernel bits, listed for completeness
MS_SUBMOUNT = 1 << 26
MS_BORN = 1 << 29
MS_ACTIVE = 1 << 30
MS_NOUSER = 1 << 31

# Bits changeable through MS_REMOUNT
MS_RMT_MASK = MS_RDONLY | MS_SYNCHRONOUS | MS_MANDLOCK | MS_I_VERSION | MS_LAZYTIME

# Legacy magic bits
MS_MGC_VAL = 0xC0ED0000
MS_MGC_MSK = 0xFFFF0000

# umount2(2) flags
MNT_FORCE = 1
MNT_DETACH = 2
MNT_EXPIRE = 4
UMOUNT_NOFOLLOW = 8

# AT_* bits shared by open_tree(2), mount_setattr(2) and friends
AT_FDCWD = -100
AT_SYMLINK_NOFOLLOW = 0x100
AT_SYMLINK_FOLLOW = 0x400
AT_NO_AUTOMOUNT = 0x800
AT_EMPTY_PATH = 0x1000
AT_RECURSIVE = 0x8000

# open_tree(2) flags
OPEN_TREE_CLONE = 1 << 0
OPEN_TREE_NAMESPACE = 1 << 1
OPEN_TREE_CLOEXEC = os.O_CLOEXEC

# move_mount(2) flags
MOVE_MOUNT_F_SYMLINKS = 0x00000001
MOVE_MOUNT_F_AUTOMOUNTS = 0x00000002
MOVE_MOUNT_F_EMPTY_PATH = 0x00000004
MOVE_MOUNT_T_SYMLINKS = 0x00000010
MOVE_MOUNT_T_AUTOMOUNTS = 0x00000020
MOVE_MOUNT_T_EMPTY_PATH = 0x00000040
MOVE_MOUNT_SET_GROUP = 0x00000100
MOVE_MOUNT_BENEATH = 0x00000200

# fsopen(2) flags
FSOPEN_CLOEXEC = 0x00000001

# fsmount(2) flags
FSMOUNT_CLOEXEC = 0x00000001
FSMOUNT_NAMESPACE = 0x00000002

# fspick(2) flags
FSPICK_CLOEXEC = 0x00000001
FSPICK_SYMLINK_NOFOLLOW = 0x00000002
FSPICK_NO_AUTOMOUNT = 0x00000004
FSPICK_EMPTY_PATH = 0x00000008

# fsconfig(2) commands, enum fsconfig_command in /usr/include/linux/mount.h
FSCONFIG_SET_FLAG = 0
FSCONFIG_SET_STRING = 1
FSCONFIG_SET_BINARY = 2
FSCONFIG_SET_PATH = 3
FSCONFIG_SET_PATH_EMPTY = 4
FSCONFIG_SET_FD = 5
FSCONFIG_CMD_CREATE = 6
FSCONFIG_CMD_RECONFIGURE = 7
FSCONFIG_CMD_CREATE_EXCL = 8

# MOUNT_ATTR_* bits for fsmount(2) and mount_setattr(2)
MOUNT_ATTR_RDONLY = 0x00000001
MOUNT_ATTR_NOSUID = 0x00000002
MOUNT_ATTR_NODEV = 0x00000004
MOUNT_ATTR_NOEXEC = 0x00000008
MOUNT_ATTR__ATIME = 0x00000070  # mask covering the three atime bits
MOUNT_ATTR_RELATIME = 0x00000000
MOUNT_ATTR_NOATIME = 0x00000010
MOUNT_ATTR_STRICTATIME = 0x00000020
MOUNT_ATTR_NODIRATIME = 0x00000080
MOUNT_ATTR_IDMAP = 0x00100000
MOUNT_ATTR_NOSYMFOLLOW = 0x00200000

# Bit position of the atime field inside MOUNT_ATTR__ATIME
MOUNT_ATTR_ATIME_SHIFT = 4

# sizeof first published struct mount_attr
MOUNT_ATTR_SIZE_VER0 = 32
